site_name: DVRPC LINK Documentation
theme: 
  features:
    - navigation.path
    - navigation.expand
    - navigation.top
  font:
    text: Roboto
  name: material
  palette:
    - scheme: default
      primary: custom
      accent: green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: custom
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
nav:
    - Home: index.md
    - Getting Started:
        - Create an account: getting-started/create-account.md
        - Draw your First Segment: getting-started/draw-first-seg.md
        - Drawing Multiple Segments: getting-started/analyzing-multiple-segments.md
        - Interpreting the Results: getting-started/Interpreting-the-results.md
        - Download and Use the Results: getting-started/download-and-use.md
    - How it works:
        - Level of Traffic Stress (LTS): how-it-works/lts.md
        - Islands of Connectivity : how-it-works/islands.md
        - What about Sidewalks? : how-it-works/sidewalk.md
    - Scaling up:
        - Uploading a GeoJSON: upload/Uploading-geometry.md
extra_css:
  - stylesheets/extra.css
